In [118]:
import torch
import numpy as np

In [66]:
print(torch.__version__)

1.13.1+cu116


# Tensors

In [67]:
# scalar 

scalar = torch.tensor(5)
print(scalar)

tensor(5)


In [68]:
print(scalar.ndim)
print(scalar.item())

0
5


In [69]:
# vector 

vector = torch.tensor([2, 3])
print(vector)
print(vector.ndim)
print(vector.shape)

assert vector.ndim == len(vector.shape), "False"

tensor([2, 3])
1
torch.Size([2])


In [70]:
# matrix 

matrix = torch.tensor([[[2, 3, 1], [7, 1, 8]], [[5, 6, 0], [5, 1, 7]]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

assert matrix.ndim == len(matrix.shape), "False"

tensor([[[2, 3, 1],
         [7, 1, 8]],

        [[5, 6, 0],
         [5, 1, 7]]])
3
torch.Size([2, 2, 3])


In [71]:
print(matrix[0], matrix[1], sep='\n')
print()

for i in matrix[0]:
    print(i)

tensor([[2, 3, 1],
        [7, 1, 8]])
tensor([[5, 6, 0],
        [5, 1, 7]])

tensor([2, 3, 1])
tensor([7, 1, 8])


In [72]:
# random tensors

random_tensor = torch.rand((3, 4, 4))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.2842, 0.8155, 0.0713, 0.2289],
         [0.2601, 0.5805, 0.3296, 0.9647],
         [0.6698, 0.2956, 0.4714, 0.4178],
         [0.6307, 0.3366, 0.8256, 0.7472]],

        [[0.5590, 0.8906, 0.9848, 0.1645],
         [0.0196, 0.8343, 0.0992, 0.9610],
         [0.9162, 0.0197, 0.5618, 0.4393],
         [0.5369, 0.5446, 0.0642, 0.4752]],

        [[0.8982, 0.8206, 0.6181, 0.0990],
         [0.7012, 0.8461, 0.1691, 0.9399],
         [0.9992, 0.4046, 0.6150, 0.8839],
         [0.2830, 0.3641, 0.9071, 0.2438]]])
3
torch.Size([3, 4, 4])


In [73]:
# random tensor with similar shape to and image

random_image_size_tensor = torch.rand((224, 224, 3))  # height, width, color channel   
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [74]:
# tensor with zeros and ones

tensor_with_zeros = torch.zeros((2, 3, 2))
print(tensor_with_zeros, tensor_with_zeros.shape)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]) torch.Size([2, 3, 2])


In [75]:
# multiply with random tensor 

tensor_with_zeros = torch.zeros(3, 5)
random_tensor = torch.rand(3, 5)
multiply = tensor_with_zeros * random_tensor

print(multiply, 
      tensor_with_zeros.shape, 
      random_tensor.shape,
      tensor_with_zeros.shape,
      multiply.shape,
      sep='\n'
      )

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([3, 5])
torch.Size([3, 5])
torch.Size([3, 5])
torch.Size([3, 5])


In [76]:
tensor_with_ones = torch.ones(3, 5)
random_tensor = torch.rand(3, 5)
multiply = tensor_with_ones * random_tensor

print(multiply,
      tensor_with_ones.shape,
      random_tensor.shape, 
      multiply.shape,
      sep='\n'
      )

print(random_tensor, multiply, sep='\n')

tensor([[0.5919, 0.9063, 0.7029, 0.7377, 0.4073],
        [0.1947, 0.8036, 0.3683, 0.1539, 0.3150],
        [0.5010, 0.6863, 0.5030, 0.8894, 0.7581]])
torch.Size([3, 5])
torch.Size([3, 5])
torch.Size([3, 5])
tensor([[0.5919, 0.9063, 0.7029, 0.7377, 0.4073],
        [0.1947, 0.8036, 0.3683, 0.1539, 0.3150],
        [0.5010, 0.6863, 0.5030, 0.8894, 0.7581]])
tensor([[0.5919, 0.9063, 0.7029, 0.7377, 0.4073],
        [0.1947, 0.8036, 0.3683, 0.1539, 0.3150],
        [0.5010, 0.6863, 0.5030, 0.8894, 0.7581]])


In [77]:
print(
    tensor_with_zeros.dtype,
    tensor_with_ones.dtype
    )

torch.float32 torch.float32


In [78]:
# tensor with range

tensor_one_to_ten = torch.arange(start=0, end=11, step=2)
print(tensor_one_to_ten)

ten_zeros = torch.zeros_like(tensor_one_to_ten)
print(ten_zeros)

tensor([ 0,  2,  4,  6,  8, 10])
tensor([0, 0, 0, 0, 0, 0])


In [79]:
# tensor data types

float_32_tensor = torch.tensor([[3, 4], [4, 5]], dtype=None)
print(float_32_tensor.dtype)

float_32_tensor = torch.tensor([[3., 4], [4, 5]], dtype=None)
print(float_32_tensor.dtype)

float_32_tensor = torch.tensor([[3, 4], [4, 5]], dtype=torch.float16)
print(float_32_tensor.dtype)

try:
    float_32_tensor = torch.tensor([[3, 4], [4, 5]], dtype=torch.float64,
                                   device="cuda", requires_grad=False)
    print(float_32_tensor.dtype)
except Exception as e:
    print("No GPU Found")

int_64_tensor = torch.tensor([[3, 4], [4, 5]], 
                               dtype=None,
                               device="cpu", 
                               requires_grad=False # whether or not 
                               # to track gradients with this tensor
                               ) 
print(int_64_tensor.dtype)

torch.int64
torch.float32
torch.float16
No GPU Found
torch.int64


In [80]:
float_32_tensor = int_64_tensor.type(torch.float32)
float_32_tensor, float_32_tensor.dtype

(tensor([[3., 4.],
         [4., 5.]]), torch.float32)

In [81]:
float32_tensor = int_64_tensor.type(torch.float32)
float16_tensor = int_64_tensor.type(torch.float16)

multiply = float32_tensor * float16_tensor
print(
    multiply, 
    multiply.dtype,
    sep='\n'
    )

tensor([[ 9., 16.],
        [16., 25.]])
torch.float32


In [82]:
multiply.device

device(type='cpu')

# Manipulating Tensors

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [83]:
tensor = torch.rand((4, 5))
print(
    tensor,
    tensor + 0.15,
    tensor - 0.23,
    tensor * 10,
    tensor / 5,
    '\n',
    tensor.add(0.15),
    tensor.subtract(0.23),
    tensor.mul(10),
    tensor.divide(5),
    sep='\n'
)

tensor([[0.5650, 0.1069, 0.3963, 0.7396, 0.6339],
        [0.1439, 0.7126, 0.9371, 0.3854, 0.4073],
        [0.8992, 0.3373, 0.5667, 0.9626, 0.0215],
        [0.2074, 0.8326, 0.7037, 0.8570, 0.2044]])
tensor([[0.7150, 0.2569, 0.5463, 0.8896, 0.7839],
        [0.2939, 0.8626, 1.0871, 0.5354, 0.5573],
        [1.0492, 0.4873, 0.7167, 1.1126, 0.1715],
        [0.3574, 0.9826, 0.8537, 1.0070, 0.3544]])
tensor([[ 0.3350, -0.1231,  0.1663,  0.5096,  0.4039],
        [-0.0861,  0.4826,  0.7071,  0.1554,  0.1773],
        [ 0.6692,  0.1073,  0.3367,  0.7326, -0.2085],
        [-0.0226,  0.6026,  0.4737,  0.6270, -0.0256]])
tensor([[5.6500, 1.0690, 3.9631, 7.3958, 6.3387],
        [1.4391, 7.1263, 9.3713, 3.8536, 4.0727],
        [8.9921, 3.3729, 5.6666, 9.6258, 0.2154],
        [2.0736, 8.3257, 7.0366, 8.5703, 2.0441]])
tensor([[0.1130, 0.0214, 0.0793, 0.1479, 0.1268],
        [0.0288, 0.1425, 0.1874, 0.0771, 0.0815],
        [0.1798, 0.0675, 0.1133, 0.1925, 0.0043],
        [0.0415, 0.1665, 0

In [84]:
# matrix multiplication 

tensor1 = torch.rand((3, 4))
tensor2 = torch.rand((4, 3))
multiply = torch.matmul(tensor1, tensor2)

print(
    tensor1,
    tensor2,
    multiply,
    tensor1 @ tensor2,
    sep='\n'
)

tensor([[0.3887, 0.9307, 0.3257, 0.9333],
        [0.2141, 0.7878, 0.3968, 0.6610],
        [0.2286, 0.7795, 0.7902, 0.1354]])
tensor([[0.9741, 0.3180, 0.7857],
        [0.7021, 0.9795, 0.6103],
        [0.0032, 0.1662, 0.5744],
        [0.6758, 0.3025, 0.2835]])
tensor([[1.6638, 1.3716, 1.3251],
        [1.2096, 1.1056, 1.0643],
        [0.8640, 1.0085, 1.1476]])
tensor([[1.6638, 1.3716, 1.3251],
        [1.2096, 1.1056, 1.0643],
        [0.8640, 1.0085, 1.1476]])


In [85]:
# transpose matrix

tensor1 = torch.rand((3, 4))
tensor1_T = tensor1.T
tensor2 = torch.rand((3, 4))
multiply = torch.matmul(tensor1_T, tensor2)

print(
    tensor1,
    tensor1_T,
    tensor2,
    multiply,
    tensor1_T @ tensor2,
    sep='\n'
)

tensor([[0.7296, 0.4123, 0.6716, 0.0348],
        [0.3520, 0.6751, 0.2074, 0.1489],
        [0.0757, 0.4689, 0.3013, 0.9265]])
tensor([[0.7296, 0.3520, 0.0757],
        [0.4123, 0.6751, 0.4689],
        [0.6716, 0.2074, 0.3013],
        [0.0348, 0.1489, 0.9265]])
tensor([[0.8163, 0.9389, 0.6680, 0.7832],
        [0.0524, 0.3967, 0.6791, 0.1385],
        [0.1084, 0.3540, 0.9691, 0.7270]])
tensor([[0.6222, 0.8514, 0.7998, 0.6752],
        [0.4227, 0.8209, 1.1884, 0.7573],
        [0.5918, 0.8195, 0.8815, 0.7738],
        [0.1367, 0.4197, 1.0223, 0.7214]])
tensor([[0.6222, 0.8514, 0.7998, 0.6752],
        [0.4227, 0.8209, 1.1884, 0.7573],
        [0.5918, 0.8195, 0.8815, 0.7738],
        [0.1367, 0.4197, 1.0223, 0.7214]])


# tensor aggregation

1. Min
2. Max
3. Mean
4. Sum

In [86]:
tensor = torch.tensor([[1, 2, 3, 4], 
                       [5, 6, 7, 8], 
                       [9, 0, 1, 5]]).type(torch.int64)
mini = torch.min(tensor)
maxi = torch.max(tensor)
sum = torch.sum(tensor)

try:
    mean = torch.mean(tensor)
except Exception as e:
    print(e)
finally:
    mean = torch.mean(tensor.type(torch.float32))

print(
    tensor,
    mini,
    maxi,
    mean,
    sum,
    sep='\n'
)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 5]])
tensor(0)
tensor(9)
tensor(4.2500)
tensor(51)


In [87]:
# finding positional max min position

print(
    tensor.argmin(),
    tensor.argmax(),
    sep='\n'
)

tensor(9)
tensor(8)


# reshaping, stacking, squeezing and unsqueezing

1. reshaping: reshapes an input tensor to a defined shape
2. view: return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. stacking: combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. squeeze: removes all `1` dimensions from a tensor
5. unsqueeze: add a `1` dimension to a target tensor
6. permute: return a view of the input with dimensions permuted 

In [88]:
tensor = torch.rand((3, 4))
tensor, tensor.shape

(tensor([[0.9814, 0.4108, 0.1645, 0.8409],
         [0.9845, 0.0696, 0.0531, 0.2026],
         [0.8287, 0.3984, 0.9206, 0.8241]]), torch.Size([3, 4]))

In [89]:
tensor_reshaped = tensor.reshape((2, 2, 3))
tensor_reshaped, tensor_reshaped.shape

(tensor([[[0.9814, 0.4108, 0.1645],
          [0.8409, 0.9845, 0.0696]],
 
         [[0.0531, 0.2026, 0.8287],
          [0.3984, 0.9206, 0.8241]]]), torch.Size([2, 2, 3]))

In [96]:
tensor1 = torch.rand((3, 4))
tensor2 = tensor1.view((6, 2))

print(tensor1, tensor2, sep='\n')

tensor1[1][1] = 9

print(tensor1, tensor2, sep='\n')

# view shares same memory

tensor([[0.0950, 0.2347, 0.2508, 0.3810],
        [0.1776, 0.9830, 0.3407, 0.9286],
        [0.2593, 0.6899, 0.7226, 0.8657]])
tensor([[0.0950, 0.2347],
        [0.2508, 0.3810],
        [0.1776, 0.9830],
        [0.3407, 0.9286],
        [0.2593, 0.6899],
        [0.7226, 0.8657]])
tensor([[0.0950, 0.2347, 0.2508, 0.3810],
        [0.1776, 9.0000, 0.3407, 0.9286],
        [0.2593, 0.6899, 0.7226, 0.8657]])
tensor([[0.0950, 0.2347],
        [0.2508, 0.3810],
        [0.1776, 9.0000],
        [0.3407, 0.9286],
        [0.2593, 0.6899],
        [0.7226, 0.8657]])


In [100]:
tensor = torch.rand(2, 3)
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=0)

print(tensor, tensor_stacked, sep='\n')
print(tensor.shape, tensor_stacked.shape, sep='\n')

tensor([[0.3534, 0.9717, 0.1484],
        [0.0214, 0.7208, 0.6017]])
tensor([[[0.3534, 0.9717, 0.1484],
         [0.0214, 0.7208, 0.6017]],

        [[0.3534, 0.9717, 0.1484],
         [0.0214, 0.7208, 0.6017]],

        [[0.3534, 0.9717, 0.1484],
         [0.0214, 0.7208, 0.6017]]])
torch.Size([2, 3])
torch.Size([3, 2, 3])


In [101]:
tensor = torch.rand(2, 3)
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=1)

print(tensor, tensor_stacked, sep='\n')
print(tensor.shape, tensor_stacked.shape, sep='\n')

tensor([[0.7098, 0.8741, 0.0583],
        [0.5338, 0.1392, 0.0050]])
tensor([[[0.7098, 0.8741, 0.0583],
         [0.7098, 0.8741, 0.0583],
         [0.7098, 0.8741, 0.0583]],

        [[0.5338, 0.1392, 0.0050],
         [0.5338, 0.1392, 0.0050],
         [0.5338, 0.1392, 0.0050]]])
torch.Size([2, 3])
torch.Size([2, 3, 3])


In [109]:
tensor1 = torch.arange(start=0, end=11, step=1)
tensor2 = tensor1.reshape(1, 1, 11)   # squeeze
tensor3 = tensor2.reshape(11)         # unsqueeze

tensor4 = tensor2.squeeze()
tensor5 = tensor4.unsqueeze(dim=0)

print(tensor1, tensor2, tensor3, tensor4, tensor5, sep='\n')

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [116]:
tensor1 = torch.rand(2, 2, 3)
tensor2 = torch.permute(tensor1, (2, 0, 1))

print(tensor1, tensor2, sep='\n')

tensor([[[0.6335, 0.0501, 0.5056],
         [0.6261, 0.0966, 0.8735]],

        [[0.6413, 0.5068, 0.0854],
         [0.7822, 0.7198, 0.7335]]])
tensor([[[0.6335, 0.6261],
         [0.6413, 0.7822]],

        [[0.0501, 0.0966],
         [0.5068, 0.7198]],

        [[0.5056, 0.8735],
         [0.0854, 0.7335]]])


# Indexing

In [117]:
x = torch.rand(3, 4, 2)
print(x[0, 0, 0])

tensor(0.2025)


# PyTorch and Numpy

In [121]:
x = np.arange(1., 10)
tensor = torch.from_numpy(x)

print(tensor, x)
print(tensor.dtype, x.dtype)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64) [1. 2. 3. 4. 5. 6. 7. 8. 9.]
torch.float64 float64


# Reproducibility

In [124]:
seed = 43

torch.manual_seed(seed)
x = torch.rand(3, 3)

torch.manual_seed(seed)
y = torch.rand(3, 3)

print(x, y, sep='\n')

tensor([[0.4540, 0.1965, 0.9210],
        [0.3462, 0.1481, 0.0858],
        [0.5909, 0.0659, 0.7476]])
tensor([[0.4540, 0.1965, 0.9210],
        [0.3462, 0.1481, 0.0858],
        [0.5909, 0.0659, 0.7476]])
